### ISSUE TITLE
Delete images and csvs on download

### ISSUE THREAD

**Issue by abfleishman** [olgaliak/active-learning-detect#10]
After getting the workflow running, I have been impressed with the ease of training, reviewing, and retraining a model. I will add ideas here for improved flow.

on the tagging computer currently, we need to delete the csvs in the `tag` folder and the images and json in the `tagging_location` before running `download_vott_json.py` and beginning a new round of tagging.  It would be nice for the files to be automatically deleted or maybe moved when running `download_vott_json.py` or at least an error that those files still exist and should be deleted prior to running the script.

**Comment by abfleishman** [comment]
I think this has been addressed @yashpande ?

**Comment by yashpande** [comment]
Looks like it.
