### ISSUE TITLE
Error with upload_vott_json.py

### ISSUE THREAD

**Issue by GondekNP** [olgaliak/active-learning-detect#28]
Abram and I are having an issue getting the VoTT workflow set up on a second windows machine. Downloading the images and tagging works just fine, the json is properly updated after tagging, but tagging.csv is never updated with the script, and tagged.csv is not created. We made sure all of the modules we needed are up to date, and our parameters are set properly in our config_cats.ini file, and we aren't sure what else to try. 

![Here's an image of the error](https://user-images.githubusercontent.com/20877429/46040576-89ee8280-c0c5-11e8-8aa9-e5cfc6e75d88.png)

**Comment by yashpande** [comment]
Yeah the issue probably occurred because the version of python that you were running this with was <3.6. Some of the code requires 3.6+ to work correctly, which can be fixed by directly using the python 3.6/3.7 executable instead of simply typing python.
