### ISSUE TITLE
Question regarding the use of Azure in this project

### ISSUE THREAD

**Issue by MatthewTafazoli** [olgaliak/active-learning-detect#52]
Hello,

I am currently doing preliminary research into a project similar to this and had some questions regarding the cloud aspect.

I saw that your project used Azure in particular as your cloud service of choice, and I was wondering if there were particular benefits to using Azure over AWS/GCP in this specific case. Also, as this project was done 3 years, have the services/options changed significantly since then? 

Thank You and Best Regards,

Matthew

**Comment by yashpande** [comment]
Hi! This work was done by people on the Microsoft CSE team (see our blog post here: https://devblogs.microsoft.com/cse/2018/11/06/active-learning-for-object-detection/) so Azure was a natural choice of cloud service and the one we were most familiar with. That being said, most of this code is platform agnostic. The tensorflow code can be run on any GPU machine, including the GPU machines provided by any cloud provider. One benefit that Azure DSVMs have is that they are preconfigured for AI development with all the necessary software packages and drivers installed; this feature may not be available with other cloud providers (you'll have to check and see). Similarly, while the custom vision code was written for the Azure custom vision API, most of the big cloud providers offer similar alternatives. That being said, you should compare the APIs to see which pricing/speed/feature set matches your needs, as well as experimentally test them to see which seems to be performing best on your dataset.
